Blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'Blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('new_author/', views.new_author, name='new_author'),
]

posts/models.py
from django.db import models
import datetime
from django.utils import timezone

class Author(models.Model):
    name = models.CharField(max_length=200)
    bio = models.TextField(max_length=2000)

    def __str__(self):
        return self.name

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    created_date = models.DateTimeField('date published')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_title(self):
        return self.title

    def was_published_recently(self):
        return self.created_date >= timezone.now() - datetime.timedelta(days=1)

posts/forms.py
from django import forms
from .models import BlogPost, Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ("name", "bio")


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ("title", "description", 'author')

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Author, BlogPost
from .forms import BlogPostForm, AuthorForm
from datetime import timezone
from django.utils import timezone

def index(request):
    latest_blog_list = BlogPost.objects.order_by('-created_date')[:10]
    context = {'latest_blog_list': latest_blog_list}
    return render(request, 'posts/index.html', context)

def detail(request, question_id):
    try:
        blogpost = BlogPost.objects.get(pk=question_id)
    except BlogPost.DoesNotExist:
        raise Http404("Blog Post does not exist")
    return render(request, 'posts/detail.html', {'blogpost': blogpost})

# def new(request):
#     form = BlogPostForm()
#     return render(request, 'posts/new.html', {'form': form})


def new(request):
    if request.method == "POST":
        form = BlogPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_date = timezone.now()
            post.save()
            return redirect('/posts/')
    else:
        form = BlogPostForm()
    return render(request, 'posts/new.html', {'form': form})

def new_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.created_date = timezone.now()
            post.save()
            return redirect('/posts/')
    else:
        form = AuthorForm()
    return render(request, 'posts/new_author.html', {'form': form})

posts/templates/posts/detail.html
<h1>{{ blogpost.title }}</h1>
    <body>{{ blogpost.description }}</body>
    <p>{{ blogpost.author }}</p>
    <p>{{ blogpost.created_date }}</p>

posts/templates/posts/index.html
{% if latest_blog_list %}
    <ul>
    {% for b in latest_blog_list %}
        <li><a href="{% url 'Blog:detail' b.id %}">{{ b.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No blog posts are available.</p>
{% endif %}

<a href="{% url 'Blog:new' %}">Create a new post</a>
<a href="{% url 'Blog:new_author' %}">New Author</a>

posts/templates/posts/new.html
{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

posts/templates/posts/new_author.html
{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}